import os
from PIL import Image

def resize_icon():
    # Source image path (generated by Gemini)
    src_path = r"C:\Users\shami\.gemini\antigravity\brain\bffb957a-b415-46b5-8479-1b0d16a1c2f2\cassandra_crystal_ball_icon_1782810670270.png"
    
    if not os.path.exists(src_path):
        print(f"Error: Source image not found at {src_path}")
        return
        
    # Output icons directory
    icons_dir = os.path.join(os.path.dirname(__file__), "icons")
    os.makedirs(icons_dir, exist_ok=True)
    
    # Load and convert to RGBA
    img = Image.open(src_path).convert("RGBA")
    
    sizes = [16, 48, 128]
    for size in sizes:
        # Resize using Lanczos resampling for high quality downscaling
        resized_img = img.resize((size, size), Image.Resampling.LANCZOS)
        out_path = os.path.join(icons_dir, f"icon{size}.png")
        resized_img.save(out_path, "PNG")
        print(f"Resized and saved: {out_path} ({size}x{size})")

if __name__ == "__main__":
    resize_icon()
